- README.md
- cli/cli.go
- goad.go
- helpers/stringsliceflag.go
- lambda/lambda.go
Using the `-H` command line switch
-  had to refactor the lamdba.go to use flags instead of os.Args[], to simplify the identification of the arguments being passed and to make it easier to pass multiple times the same flag
> Added the possibility of passing custom headers

- goad.go
- infrastructure/infrastructure.go
- version/version.go
So that new goad releases update the lambda code and invoke the correct
version. Using multiple versions of goad is also supported.
> Version lambda functions

- goad.go
- infrastructure/infrastructure.go
Use passed AWS config and do not recreate new one.
Fix #34
> Fix AWS profiles.

- goad.go
increase limits and number of instances for better stability on high concurrency loads.
When i increase the number of concurrency requests, lambda start to gave errors, even if the remote server is able to sustain the requests. Increasing the number of instances in the lambda turns the service and requests more stable 
With this change, i can get this:
```
./goad  -r eu-central-1,us-east-1,eu-west-1,ap-northeast-1,us-west-2 -c 120000  -n 600000    -u https://test.xxxxxx.com/favicon.ico
TotReqs   TotBytes    AvgTime   AvgReq/s  AvgKbps/s
599967     3.3 GB     0.853s  286248.47 1517898.75
Slowest    Fastest   Timeouts  TotErrors
14.911s     0.015s          1         27
HTTPStatus   Requests
200     599940
```
where in the default limit, i get 50% of errors with the same parameters
The …
> increase limits and number of instances 

- cli/cli.go
I was hoping to interact with goad programatically, so I could do something like (pseudocode)
```
for a range of concurrency levels
run a goad test
if the results are sufficiently bad, return
```
This way I can determine the breaking points (timeouts, error codes, under-SLA performance) of various architectures relatively unattended. All that was really needed beyond the basic existing goad plumbing was an easy way of parsing the results. Instead of scraping the output format, it seemed straightforward to add a JSON output option, which could also easily lead to post-run result saving, or charting, or any number of other use cases.
```
$ goad -c 15 -n 50 -u testdomain.com -o results.json
$ goad -c 15 -n 50 -u testdomain.com -o ~/testdomain_perf/goad-$(date +"%Y_%m_%d-%H_%m_%S").json …
```
> Added optional json output of results (`-o` flag)

- lambda/lambda.go
#39 User-Agent header is hardcoded
> Using the user-agent informed for the user

- goad.go
- infrastructure/infrastructure.go
the threads were concurrently swapping region
to each other in the config AWS obj... fun :(
> BUG! preventing multiregion to work

- infrastructure/infrastructure.go
for new accounts on AWS it is not possible anymore to use goad as is: they deprecated the runtime environment parameter that was given at lambda function creation
plus, the reattempt function that was being executed in case of failure was causing an infinite loop of calls that hided the error from the user...
> deprecated AWS api parameter value: nodejs vs nodejs4.3

- data/lambda/index.js
seems that after a generous amount of output we <br>end up consuming the buffer of the exec() method
my colleague @Savar initially patched it raising such limit, <br>then he completely refactored it in a safer way
similar issue:  
- http://stackoverflow.com/questions/23429499/stdout-buffer-issue-using-node-child-process
> buffer maxSize reached, refactored

- cli/cli.go
- goad.go
- helpers/int64slice.go
- lambda/lambda.go
- queue/aggregation.go
Highlights on Issue #12 resolution:
We had to make a decision on how to compute the percentiles, in this case, we opted to match Apache Benchmark scores distribution (50%, 66%, 75%, 80%, 90%, 95%, 99% & 100%) - this can be modified on queue/aggregation.go on line 13 (if you guys want to match exactly as the conversation going on @GitHub)
The Percentile option was added as a paramenter "-i" with false as default. We would liked to use "-p", but it was already in use.
Finally, to calculate the percentile, we took the approach of accumulating the stats to produce partials and final numbers in queue/aggregation.go 
We thought that HDR Histogram will introduce extra complexity (and computational cost, being lambda sensible in regards to runtime).
Now the trade-off of this approach in numbers …
> Added optional display of elapsed time percentiles

- Dockerfile
- Godeps/Godeps.json
- Makefile
- goad.go
- infrastructure/infrastructure.go
- lambda/lambda.go
- lambda/lambda_test.go
- queue/aggregation.go
- queue/sqsadaptor_test.go
This pull request resolves #102 the 5 minute execution timeout that is inherent to execution of lambda functions on aws.
The commit introduces a lot of changes to lambda/lambda.go mainly because the code execution paths became increasingly hard to follow. To make changes without introducing breaking changes to the API a small suite of unit tests was added to accompany the refactoring.
This commit also fixes a bug terminating the CLI to early when more then one lambda is running in a region.
Functional changes are:
* execution timeout of AWS lambda functions no longer stops execution of long running load tests
* the CLI introduces a limit for total execution of 60 minutes
* setup infrastructure permissions to spawn new lambda from existing lambda
* allow execution by time rather than …
> break 5min lambda barrier

- HomebrewFormula/goad.rb
We are using a tagged version to comply to homebrew-core standards.
> update homebrew formula with tag

- HomebrewFormula/goad.rb
- Makefile
To address the second issue in our [Pull Request](https://github.com/Homebrew/homebrew-core/pull/13162) to hombrew-core. I've added a fixed revision of go-bindata to the build process.
Well need to tag the merged release with 1.4.1.
> Update homebrew recipe to be compliant for hombrew-core

- lambda/lambda.go
- queue/aggregation.go
- queue/sqsadaptor.go
- queue/sqsadaptor_test.go
The SQS Adapter was misspelled and the unit test was not updated for a changes in the data structure.
The test is actually valuable because is specifies the SQS exchange format between lambda and CLI.
> Fix sqsadapter name and test

- .travis.yml
- DEBIAN/control
- DEBIAN/copyrigth
- Makefile
This PR addresses #126 by providing new build targets for debian and rpm packages in the Makefile.
The generated packages are fairly minimal containing just the goad binary for the according architecture. Relying on `alien` to generate the rpm packages from the generated deb packages.
The travis-ci build file is slightly modified to output these new build artifacts and to install the required packages for the build process.
The zip files with the build for the linux platform have not yet been removed from the build process.
> Build .deb and .rpm packages

- README.md
- cli/cli.go
- cli/config_template.go
- cli/ini_parser_test.go
- cli/testdata/default.ini
This adds the `--create-ini-template` to the cli
allowing users to create a sample configuration for
goad in their current working directory.
> Add new options flag to create sample configuration

- Makefile
- version/version.go
Fixes #151 but needs to be tested on a non release build first to verify if this works as expected.
If the TRAVIS_TAG environment variable is present we use this to set the version reported by the cli.
> Use git tag when building goad with travis

- infrastructure/docker/docker.go
Fix #172
Refactoring of the infrastructure code has left the docker mode in a non working state due to pointer reference errors.
> Fix run-docker experimental mode

- infrastructure/aws/aws.go
the node 4.3 runtime is no longer available on aws, this PR uses the latest version
> fixing node version error

- README.md
There was an error in an example in the README file.
> fix: remove legacy -u argument in goad example
